
package com.nuri.etk.async.ws.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2018-11-23T16:23:47.952+09:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "Exception", targetNamespace = "http://server.ws.command.fep.aimir.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.nuri.etk.async.ws.client.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.nuri.etk.async.ws.client.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.nuri.etk.async.ws.client.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.nuri.etk.async.ws.client.Exception getFaultInfo() {
        return this.exception;
    }
}
